import { Badge } from '../../components/primitives/Badge'
import { Button } from '../../components/primitives/Button'
import { Icon } from '../../components/primitives/Icon'
import type { ConceptDetail } from '../../domain/knowledge'
import { ConceptBadge } from './ConceptBadge'

export function ConceptPanel({ concept, onClose, onOpenDocument, onOpenConcept, onAsk }: { concept: ConceptDetail; onClose: () => void; onOpenDocument: (id: number) => void; onOpenConcept: (id: number) => void; onAsk: (value: string) => void }) {
  return <aside className="context-panel" aria-label="개념 상세"><div className="panel-topline"><Badge tone="teal"><Icon name="concept" /> CONCEPT NODE</Badge><button className="icon-button" type="button" onClick={onClose} aria-label="패널 닫기"><Icon name="close" /></button></div><div className="concept-hero"><span className={`concept-orb type-${concept.concept_type}`}><Icon name="concept" /></span><ConceptBadge type={concept.concept_type} /><h2>{concept.canonical_name}</h2><p>{concept.description}</p>{concept.english_name && <span className="alternate-name">{concept.english_name}{concept.abbreviation ? ` · ${concept.abbreviation}` : ''}</span>}</div><div className="panel-actions"><Button variant="primary" size="sm" onClick={() => onAsk(`${concept.canonical_name}에 대해 저장된 지식으로 설명해줘`)}><Icon name="spark" /> 이 개념으로 질문</Button><Button variant="ghost" size="sm"><Icon name="orbit" /> 중심에 놓기</Button></div><div className="panel-section"><div className="section-label-row"><span className="section-label">다른 이름</span><small>{concept.aliases.length}</small></div><div className="alias-list">{concept.aliases.map((alias) => <span key={`${alias.alias}-${alias.alias_type}`}>{alias.alias}<small>{alias.alias_type}</small></span>)}</div></div><div className="panel-section"><div className="section-label-row"><span className="section-label">발견된 자료</span><small>{concept.source_chunks.length} chunks</small></div><div className="source-document-list">{concept.source_chunks.map((chunk) => <button type="button" key={chunk.id} onClick={() => onOpenDocument(chunk.document_id)}><span><strong>#{chunk.chunk_index + 1} · {chunk.preview.slice(0, 54)}</strong><small>원문 청크 {chunk.start_char.toLocaleString()}–{chunk.end_char.toLocaleString()}</small></span><Icon name="chevron" /></button>)}</div></div><div className="panel-section"><div className="section-label-row"><span className="section-label">함께 연결된 개념</span><small>{concept.related_concepts.length}</small></div><div className="related-concept-list">{concept.related_concepts.map((relation) => <button type="button" key={relation.concept.id} onClick={() => onOpenConcept(relation.concept.id)}><span><strong>{relation.concept.canonical_name}</strong><small>{relation.relation_type} · {Math.round(relation.strength * 100)}%</small></span><Icon name="chevron" /></button>)}</div></div></aside>
}
